const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')

;(async () => {
  require('node:fs').mkdirSync('artifacts', { recursive: true })
  const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}) })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  const requests = []
  let failNext = false
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    requests.push(url)
    if (url.pathname === '/api/article-preview') return route.fulfill({ json: { status: 'success', data: { image_url: null } } })
    if (url.pathname === '/api/read') return route.fulfill({ json: { status: 'error', message: 'Publisher unavailable. Open the original article.' } })
    if (url.pathname.includes('collections') || url.pathname.includes('bookmarks')) return route.fulfill({ json: { status: 'success', data: [] } })
    if (failNext && url.searchParams.get('page') === '2') {
      failNext = false
      return route.fulfill({ status: 503, json: { detail: 'Test source unavailable' } })
    }
    const current = Number(url.searchParams.get('page') || 1)
    const topic = url.searchParams.get('q') || url.pathname.split('/').at(-1)
    if (topic === 'world') await new Promise(resolve => setTimeout(resolve, 400))
    const headlines = ['The next chapter of technology is taking shape', 'A closer look at the ideas changing our everyday lives', 'Researchers find a new way to understand our world']
    const data = Array.from({ length: current === 1 ? 20 : 5 }, (_, i) => ({ id: `${topic}-${current}-${i}`, url: `https://example.org/${topic}/${current}/${i}`, title: `${headlines[i % 3]} / ${topic} ${current}-${i}`, source: ['The Perspective', 'Science Daily', 'World Review'][i % 3], description: 'The people, discoveries, and decisions behind today’s headlines. Get the context that helps you see the bigger picture.', published_at: '2026-09-14T10:30:00Z' }))
    await route.fulfill({ json: { status: 'success', data, has_more: current === 1, next_page: current === 1 ? 2 : null, next_after: current === 1 ? `${topic}-edition` : null, updated_at: '2026-09-14T12:00:00Z' } })
  })
  await page.goto('http://127.0.0.1:5173')
  await page.locator('.card').nth(19).waitFor()
  await page.getByRole('button', { name: /Read & Summarize/ }).click()
  await page.getByRole('dialog').getByText('Publisher unavailable. Open the original article.').waitFor()
  assert.ok(await page.getByRole('link', { name: 'Open original article', exact: true }).last().getAttribute('href'))
  await page.locator('.modal__close').click()
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: false })
  failNext = true
  await page.locator('.scroll-sentinel').scrollIntoViewIfNeeded()
  await page.getByRole('alert').waitFor()
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await page.locator('.card').nth(24).waitFor()
  assert.equal(await page.locator('.card').count(), 25)
  assert.ok(requests.some(u => u.searchParams.get('after') === 'technology-edition'))
  await page.getByRole('button', { name: 'World', exact: true }).click()
  await page.getByRole('button', { name: 'Science', exact: true }).click()
  await page.locator('.card').first().filter({ hasText: 'science' }).waitFor()
  assert.equal(await page.locator('.card').filter({ hasText: '/ world' }).count(), 0)
  await page.getByRole('textbox', { name: 'Search stories' }).fill('space')
  await page.getByRole('textbox', { name: 'Search stories' }).press('Enter')
  await page.locator('.card').first().filter({ hasText: '/ space' }).waitFor()
  await page.getByRole('textbox', { name: 'Search stories' }).fill('unsubmitted')
  await page.locator('.scroll-sentinel').scrollIntoViewIfNeeded()
  await page.locator('.card').nth(24).waitFor()
  assert.ok(requests.some(u => u.searchParams.get('q') === 'space' && u.searchParams.get('page') === '2'))
  assert.ok(!requests.some(u => u.searchParams.get('q') === 'unsubmitted'))
  await page.getByRole('button', { name: 'Clear search' }).click()
  await page.locator('.card').first().filter({ hasText: '/ science' }).waitFor()
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.waitForTimeout(400)
  await page.screenshot({ path: 'artifacts/dark.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Switch to light theme' }).click()
  await page.waitForTimeout(400)
  await page.screenshot({ path: 'artifacts/mobile.png' })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  await page.getByRole('button', { name: /More/ }).click()
  await page.getByRole('button', { name: /Business/ }).click()
  await page.locator('.card').first().filter({ hasText: '/ business' }).waitFor()
  assert.deepEqual(errors, [])
  console.log('PASS: pagination, retry, cursor, rapid category changes, committed search, dark theme, mobile overflow and categories; no browser errors.')
  await browser.close()
})().catch(error => { console.error(error); process.exit(1) })
