-- Run in the Supabase SQL editor. Safe to rerun.
-- New tables deliberately keep old, shared bookmarks out of private accounts.
begin;

create table if not exists public.upfeed_collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 80),
  color text not null default '#c4451e' check (color ~ '^#[0-9a-fA-F]{6}$'),
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.upfeed_bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (length(trim(title)) between 1 and 1000),
  url text not null check (url ~ '^https?://' and octet_length(url) <= 2000),
  image_url text,
  ai_summary text,
  description text,
  source text,
  published_at timestamptz,
  collection_id bigint references public.upfeed_collections(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (user_id, url)
);

create index if not exists upfeed_bookmarks_user_created
  on public.upfeed_bookmarks (user_id, created_at desc, id desc);
create index if not exists upfeed_bookmarks_user_collection
  on public.upfeed_bookmarks (user_id, collection_id);

alter table public.upfeed_collections enable row level security;
alter table public.upfeed_bookmarks enable row level security;

revoke all on public.upfeed_collections, public.upfeed_bookmarks from public, anon, authenticated;
grant select, insert, update, delete on public.upfeed_collections, public.upfeed_bookmarks to authenticated;
grant usage, select on sequence public.upfeed_collections_id_seq, public.upfeed_bookmarks_id_seq to authenticated;

drop policy if exists upfeed_collections_owner on public.upfeed_collections;
create policy upfeed_collections_owner on public.upfeed_collections
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists upfeed_bookmarks_owner on public.upfeed_bookmarks;
create policy upfeed_bookmarks_owner on public.upfeed_bookmarks
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid()) and (
      collection_id is null or exists (
        select 1 from public.upfeed_collections c
        where c.id = collection_id and c.user_id = (select auth.uid())
      )
    )
  );

-- Retain legacy shared data but close its old anonymous API access.
do $$
begin
  if to_regclass('public.bookmarks') is not null then
    execute 'alter table public.bookmarks enable row level security';
    execute 'revoke all on public.bookmarks from public, anon, authenticated';
  end if;
  if to_regclass('public.collections') is not null then
    execute 'alter table public.collections enable row level security';
    execute 'revoke all on public.collections from public, anon, authenticated';
  end if;
end $$;

notify pgrst, 'reload schema';
commit;
